name: Playwright Tests

on:
  push:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run FOX HOME login monitoring
        run: npx playwright test tests/critical/login-id-to-otp.spec.ts --project=chromium
        env:
          SITE: foxhome